// Offline fallback used when the live job API can't be reached (no internet,
// rate limit, API change). Companies are fictional. The API response marks
// these as source: "sample" so the UI never presents them as real postings.

const d = (daysAgo) => new Date(Date.now() - daysAgo * 86_400_000).toISOString();

export const sampleJobs = [
  {
    id: 'sample-1',
    title: 'Junior Full-Stack Developer',
    company: 'Northwind Labs (sample)',
    category: 'Software Development',
    tags: ['javascript', 'react', 'node.js', 'sql'],
    location: 'Worldwide',
    jobType: 'full_time',
    salary: '',
    url: 'https://example.com/jobs/sample-1',
    postedAt: d(1),
    description:
      'Join a small product team building internal dashboards. You will work with React, Node.js and SQL databases, ship features weekly and learn from senior engineers. Recent graduates welcome.',
  },
  {
    id: 'sample-2',
    title: 'Data Analyst (Entry Level)',
    company: 'Bluebird Analytics (sample)',
    category: 'Data',
    tags: ['sql', 'python', 'excel', 'tableau'],
    location: 'Asia',
    jobType: 'full_time',
    salary: '',
    url: 'https://example.com/jobs/sample-2',
    postedAt: d(2),
    description:
      'Analyze customer data with SQL and Python, build dashboards in Tableau and present findings to business stakeholders. Strong Excel skills and curiosity required.',
  },
  {
    id: 'sample-3',
    title: 'Senior Backend Engineer',
    company: 'Quartz Systems (sample)',
    category: 'Software Development',
    tags: ['java', 'kubernetes', 'aws', 'microservices'],
    location: 'Worldwide',
    jobType: 'full_time',
    salary: '',
    url: 'https://example.com/jobs/sample-3',
    postedAt: d(3),
    description:
      'Lead the design of distributed Java microservices running on Kubernetes and AWS. 7+ years of backend experience expected, including mentoring other engineers.',
  },
  {
    id: 'sample-4',
    title: 'Frontend Developer Intern',
    company: 'Pixel Harbor (sample)',
    category: 'Software Development',
    tags: ['html', 'css', 'javascript', 'react'],
    location: 'Asia',
    jobType: 'internship',
    salary: '',
    url: 'https://example.com/jobs/sample-4',
    postedAt: d(2),
    description:
      'Six-month internship on our web team. Build accessible UI with HTML, CSS, JavaScript and React. Mentorship included, no prior professional experience needed.',
  },
  {
    id: 'sample-5',
    title: 'Business Systems Analyst',
    company: 'Meridian Logistics (sample)',
    category: 'Business',
    tags: ['sql', 'erp', 'requirements', 'agile'],
    location: 'Worldwide',
    jobType: 'full_time',
    salary: '',
    url: 'https://example.com/jobs/sample-5',
    postedAt: d(4),
    description:
      'Bridge business and engineering teams: gather requirements, model processes, write user stories and validate ERP integrations. Familiarity with SQL and agile workflows is a plus.',
  },
  {
    id: 'sample-6',
    title: 'Machine Learning Engineer',
    company: 'Helix AI (sample)',
    category: 'Data',
    tags: ['python', 'pytorch', 'machine learning', 'mlops'],
    location: 'Worldwide',
    jobType: 'full_time',
    salary: '',
    url: 'https://example.com/jobs/sample-6',
    postedAt: d(5),
    description:
      'Train and deploy models in Python and PyTorch, build data pipelines and monitor models in production. Experience with MLOps tooling preferred.',
  },
  {
    id: 'sample-7',
    title: 'QA Engineer',
    company: 'Lanternworks (sample)',
    category: 'QA',
    tags: ['testing', 'automation', 'javascript', 'selenium'],
    location: 'Asia',
    jobType: 'full_time',
    salary: '',
    url: 'https://example.com/jobs/sample-7',
    postedAt: d(6),
    description:
      'Write automated end-to-end tests with JavaScript and Selenium, triage bugs with developers and improve our release process.',
  },
  {
    id: 'sample-8',
    title: 'Product Manager, Associate',
    company: 'Cobalt Commerce (sample)',
    category: 'Product',
    tags: ['product', 'agile', 'analytics', 'communication'],
    location: 'Worldwide',
    jobType: 'full_time',
    salary: '',
    url: 'https://example.com/jobs/sample-8',
    postedAt: d(3),
    description:
      'Own a slice of the roadmap, interview users, define requirements and work with engineers and designers. Comfortable with analytics tools and SQL is a plus.',
  },
  {
    id: 'sample-9',
    title: 'DevOps Engineer',
    company: 'Ironleaf Cloud (sample)',
    category: 'DevOps',
    tags: ['docker', 'ci/cd', 'linux', 'aws'],
    location: 'Worldwide',
    jobType: 'full_time',
    salary: '',
    url: 'https://example.com/jobs/sample-9',
    postedAt: d(7),
    description:
      'Maintain CI/CD pipelines, containerize services with Docker and manage Linux servers on AWS. On-call rotation required.',
  },
  {
    id: 'sample-10',
    title: 'Junior Python Developer',
    company: 'Saffron Software (sample)',
    category: 'Software Development',
    tags: ['python', 'django', 'sql', 'git'],
    location: 'Worldwide',
    jobType: 'full_time',
    salary: '',
    url: 'https://example.com/jobs/sample-10',
    postedAt: d(1),
    description:
      'Build and maintain Django web applications backed by SQL databases. You will review code, write tests and learn modern Python practices. Graduates and career changers welcome.',
  },
];
